Skip to content
Navigation Menu
Cliffvincent
/
GOATBOTV2-BY-NTKHANG

Code
Issues
Pull requests
10
Discussions
Actions
Projects
Security
Insights
Node.js CI
Update account.txt #37
Jobs
Run details
Workflow file for this run
.github/workflows/Run.yml at b1142da
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm start
Update account.txt · Cliffvincent/GOATBOTV2-BY-NTKHANG@b1142da 
